// Generated by scripts/generate-rpc-registry.mjs. Do not edit by hand.
export type RpcArg = {
  name: string;
  type: string;
};

export type RpcSignature = {
  args: RpcArg[];
  returns: string;
  defaults: number;
};

export const RPC_REGISTRY: Record<string, RpcSignature[]> = {
  "_assert_active_connection": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        }
      ],
      "returns": "void",
      "defaults": 0
    }
  ],
  "_assert_active_session": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        }
      ],
      "returns": "void",
      "defaults": 0
    }
  ],
  "_assert_member": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        }
      ],
      "returns": "void",
      "defaults": 0
    }
  ],
  "_assert_no_active_dependents": [
    {
      "args": [
        {
          "name": "p_task_id",
          "type": "uuid"
        }
      ],
      "returns": "void",
      "defaults": 0
    }
  ],
  "_assert_owner": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        }
      ],
      "returns": "void",
      "defaults": 0
    }
  ],
  "_block_newly_unmet_dependents": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_changed_task_id",
          "type": "uuid"
        }
      ],
      "returns": "void",
      "defaults": 0
    }
  ],
  "_bridge_configuration_payload": [
    {
      "args": [
        {
          "name": "p_connection_id",
          "type": "uuid"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    },
    {
      "args": [
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_platform",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "_bridge_working_directories_are_valid": [
    {
      "args": [
        {
          "name": "p_directories",
          "type": "jsonb"
        }
      ],
      "returns": "boolean",
      "defaults": 0
    }
  ],
  "_canonical_bridge_platform": [
    {
      "args": [
        {
          "name": "p_platform",
          "type": "text"
        }
      ],
      "returns": "text",
      "defaults": 0
    }
  ],
  "_claim_next_internal": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        },
        {
          "name": "p_claim_token_hash",
          "type": "text"
        },
        {
          "name": "p_lease_seconds",
          "type": "integer"
        },
        {
          "name": "p_preferred_root_task_id",
          "type": "uuid"
        }
      ],
      "returns": "jsonb",
      "defaults": 1
    }
  ],
  "_claim_task_internal": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        },
        {
          "name": "p_task_id",
          "type": "uuid"
        },
        {
          "name": "p_claim_token_hash",
          "type": "text"
        },
        {
          "name": "p_lease_seconds",
          "type": "integer"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "_complete_task_internal": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        },
        {
          "name": "p_task_id",
          "type": "uuid"
        },
        {
          "name": "p_result_summary",
          "type": "text"
        },
        {
          "name": "p_result_json",
          "type": "jsonb"
        },
        {
          "name": "p_message_content",
          "type": "text"
        },
        {
          "name": "p_artifacts",
          "type": "jsonb"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "_connection_payload": [
    {
      "args": [
        {
          "name": "p_connection_id",
          "type": "uuid"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "_create_subtasks_internal": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_parent_task_id",
          "type": "uuid"
        },
        {
          "name": "p_subtasks",
          "type": "jsonb"
        },
        {
          "name": "p_actor_type",
          "type": "actor_type"
        },
        {
          "name": "p_actor_id",
          "type": "uuid"
        },
        {
          "name": "p_allow_existing_children",
          "type": "boolean"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "_exchange_ai_connection_bridge_config_platform": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_platform",
          "type": "text"
        },
        {
          "name": "p_runtime_instance_id",
          "type": "uuid"
        },
        {
          "name": "p_report_sequence",
          "type": "bigint"
        },
        {
          "name": "p_lease_seconds",
          "type": "integer"
        },
        {
          "name": "p_release_runtime",
          "type": "boolean"
        },
        {
          "name": "p_applied_version",
          "type": "integer"
        },
        {
          "name": "p_effective",
          "type": "jsonb"
        },
        {
          "name": "p_constraints",
          "type": "jsonb"
        },
        {
          "name": "p_error",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "_exchange_ai_connection_bridge_config_v3": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_runtime_instance_id",
          "type": "uuid"
        },
        {
          "name": "p_report_sequence",
          "type": "bigint"
        },
        {
          "name": "p_lease_seconds",
          "type": "integer"
        },
        {
          "name": "p_release_runtime",
          "type": "boolean"
        },
        {
          "name": "p_applied_version",
          "type": "integer"
        },
        {
          "name": "p_effective",
          "type": "jsonb"
        },
        {
          "name": "p_constraints",
          "type": "jsonb"
        },
        {
          "name": "p_error",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "_exchange_ai_connection_bridge_config_v4": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_runtime_instance_id",
          "type": "uuid"
        },
        {
          "name": "p_report_sequence",
          "type": "bigint"
        },
        {
          "name": "p_lease_seconds",
          "type": "integer"
        },
        {
          "name": "p_release_runtime",
          "type": "boolean"
        },
        {
          "name": "p_applied_version",
          "type": "integer"
        },
        {
          "name": "p_effective",
          "type": "jsonb"
        },
        {
          "name": "p_constraints",
          "type": "jsonb"
        },
        {
          "name": "p_error",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "_exchange_ai_connection_bridge_config_v5": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_runtime_instance_id",
          "type": "uuid"
        },
        {
          "name": "p_report_sequence",
          "type": "bigint"
        },
        {
          "name": "p_lease_seconds",
          "type": "integer"
        },
        {
          "name": "p_release_runtime",
          "type": "boolean"
        },
        {
          "name": "p_applied_version",
          "type": "integer"
        },
        {
          "name": "p_effective",
          "type": "jsonb"
        },
        {
          "name": "p_constraints",
          "type": "jsonb"
        },
        {
          "name": "p_error",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "_file_command_payload": [
    {
      "args": [
        {
          "name": "p_command_id",
          "type": "uuid"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "_idempotency_begin": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_actor_key",
          "type": "text"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_operation",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "_idempotency_finish": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_actor_key",
          "type": "text"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_response",
          "type": "jsonb"
        }
      ],
      "returns": "void",
      "defaults": 0
    }
  ],
  "_idle_session_status": [
    {
      "args": [
        {
          "name": "p_session_id",
          "type": "uuid"
        }
      ],
      "returns": "ai_session_status",
      "defaults": 0
    }
  ],
  "_insert_completion_artifacts": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_task_id",
          "type": "uuid"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        },
        {
          "name": "p_artifacts",
          "type": "jsonb"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "_lock_ai_session": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        }
      ],
      "returns": "void",
      "defaults": 0
    }
  ],
  "_lock_task_state_exclusive": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        }
      ],
      "returns": "void",
      "defaults": 0
    }
  ],
  "_lock_task_state_shared": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        }
      ],
      "returns": "void",
      "defaults": 0
    }
  ],
  "_lock_valid_claim": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        },
        {
          "name": "p_task_id",
          "type": "uuid"
        },
        {
          "name": "p_claim_token_hash",
          "type": "text"
        }
      ],
      "returns": "tasks",
      "defaults": 0
    }
  ],
  "_raise": [
    {
      "args": [
        {
          "name": "p_code",
          "type": "text"
        }
      ],
      "returns": "void",
      "defaults": 0
    }
  ],
  "_recompute_ancestors": [
    {
      "args": [
        {
          "name": "p_task_id",
          "type": "uuid"
        }
      ],
      "returns": "void",
      "defaults": 0
    }
  ],
  "_recompute_parent": [
    {
      "args": [
        {
          "name": "p_parent_task_id",
          "type": "uuid"
        }
      ],
      "returns": "void",
      "defaults": 0
    }
  ],
  "_refresh_unblocked_tasks": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_completed_task_id",
          "type": "uuid"
        }
      ],
      "returns": "void",
      "defaults": 0
    }
  ],
  "_session_payload": [
    {
      "args": [
        {
          "name": "p_session_id",
          "type": "uuid"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "_task_payload": [
    {
      "args": [
        {
          "name": "p_task_id",
          "type": "uuid"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "_task_user_input_public_payload": [
    {
      "args": [
        {
          "name": "p_request_id",
          "type": "uuid"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "_thread_command_payload": [
    {
      "args": [
        {
          "name": "p_command_id",
          "type": "uuid"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "_valid_task_user_input_answers": [
    {
      "args": [
        {
          "name": "p_questions",
          "type": "jsonb"
        },
        {
          "name": "p_answers",
          "type": "jsonb"
        }
      ],
      "returns": "boolean",
      "defaults": 0
    }
  ],
  "_valid_task_user_input_questions": [
    {
      "args": [
        {
          "name": "p_questions",
          "type": "jsonb"
        }
      ],
      "returns": "boolean",
      "defaults": 0
    }
  ],
  "answer_task_user_input_request": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        },
        {
          "name": "p_task_id",
          "type": "uuid"
        },
        {
          "name": "p_request_id",
          "type": "uuid"
        },
        {
          "name": "p_answers",
          "type": "jsonb"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "can_access_task_artifact": [
    {
      "args": [
        {
          "name": "p_object_name",
          "type": "text"
        }
      ],
      "returns": "boolean",
      "defaults": 0
    }
  ],
  "cancel_task": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        },
        {
          "name": "p_task_id",
          "type": "uuid"
        },
        {
          "name": "p_reason",
          "type": "text"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "claim_ai_file_command": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_runtime_instance_id",
          "type": "uuid"
        },
        {
          "name": "p_lease_seconds",
          "type": "integer"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "claim_ai_thread_command": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_runtime_instance_id",
          "type": "uuid"
        },
        {
          "name": "p_lease_seconds",
          "type": "integer"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    },
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_runtime_instance_id",
          "type": "uuid"
        },
        {
          "name": "p_lease_seconds",
          "type": "integer"
        },
        {
          "name": "p_platform",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "claim_next_task": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        },
        {
          "name": "p_claim_token_hash",
          "type": "text"
        },
        {
          "name": "p_lease_seconds",
          "type": "integer"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "claim_steer_task": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        },
        {
          "name": "p_claim_token_hash",
          "type": "text"
        },
        {
          "name": "p_lease_seconds",
          "type": "integer"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "claim_task": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        },
        {
          "name": "p_task_id",
          "type": "uuid"
        },
        {
          "name": "p_claim_token_hash",
          "type": "text"
        },
        {
          "name": "p_lease_seconds",
          "type": "integer"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "cleanup_expired_idempotency_records": [
    {
      "args": [
        {
          "name": "p_batch_size",
          "type": "integer"
        }
      ],
      "returns": "integer",
      "defaults": 1
    }
  ],
  "complete_ai_file_command": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_runtime_instance_id",
          "type": "uuid"
        },
        {
          "name": "p_command_id",
          "type": "uuid"
        },
        {
          "name": "p_succeeded",
          "type": "boolean"
        },
        {
          "name": "p_result",
          "type": "jsonb"
        },
        {
          "name": "p_error",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "complete_ai_thread_command": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_runtime_instance_id",
          "type": "uuid"
        },
        {
          "name": "p_command_id",
          "type": "uuid"
        },
        {
          "name": "p_succeeded",
          "type": "boolean"
        },
        {
          "name": "p_external_thread_id",
          "type": "text"
        },
        {
          "name": "p_error",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "complete_task": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        },
        {
          "name": "p_task_id",
          "type": "uuid"
        },
        {
          "name": "p_claim_token_hash",
          "type": "text"
        },
        {
          "name": "p_result_summary",
          "type": "text"
        },
        {
          "name": "p_result_json",
          "type": "jsonb"
        },
        {
          "name": "p_message_content",
          "type": "text"
        },
        {
          "name": "p_artifacts",
          "type": "jsonb"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "complete_task_and_claim_next": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        },
        {
          "name": "p_task_id",
          "type": "uuid"
        },
        {
          "name": "p_claim_token_hash",
          "type": "text"
        },
        {
          "name": "p_result_summary",
          "type": "text"
        },
        {
          "name": "p_result_json",
          "type": "jsonb"
        },
        {
          "name": "p_message_content",
          "type": "text"
        },
        {
          "name": "p_artifacts",
          "type": "jsonb"
        },
        {
          "name": "p_next_claim_token_hash",
          "type": "text"
        },
        {
          "name": "p_lease_seconds",
          "type": "integer"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "create_ai_connection": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_name",
          "type": "text"
        },
        {
          "name": "p_platform",
          "type": "text"
        },
        {
          "name": "p_token_hash",
          "type": "text"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "create_session_turn": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        },
        {
          "name": "p_title",
          "type": "text"
        },
        {
          "name": "p_content",
          "type": "text"
        },
        {
          "name": "p_priority",
          "type": "integer"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "create_session_turn_with_images": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        },
        {
          "name": "p_title",
          "type": "text"
        },
        {
          "name": "p_content",
          "type": "text"
        },
        {
          "name": "p_priority",
          "type": "integer"
        },
        {
          "name": "p_images",
          "type": "jsonb"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "create_session_turn_with_settings": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        },
        {
          "name": "p_title",
          "type": "text"
        },
        {
          "name": "p_content",
          "type": "text"
        },
        {
          "name": "p_priority",
          "type": "integer"
        },
        {
          "name": "p_images",
          "type": "jsonb"
        },
        {
          "name": "p_model",
          "type": "text"
        },
        {
          "name": "p_reasoning_effort",
          "type": "text"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    },
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        },
        {
          "name": "p_title",
          "type": "text"
        },
        {
          "name": "p_content",
          "type": "text"
        },
        {
          "name": "p_priority",
          "type": "integer"
        },
        {
          "name": "p_images",
          "type": "jsonb"
        },
        {
          "name": "p_model",
          "type": "text"
        },
        {
          "name": "p_reasoning_effort",
          "type": "text"
        },
        {
          "name": "p_goal_mode",
          "type": "boolean"
        },
        {
          "name": "p_steer",
          "type": "boolean"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    },
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        },
        {
          "name": "p_title",
          "type": "text"
        },
        {
          "name": "p_content",
          "type": "text"
        },
        {
          "name": "p_priority",
          "type": "integer"
        },
        {
          "name": "p_images",
          "type": "jsonb"
        },
        {
          "name": "p_model",
          "type": "text"
        },
        {
          "name": "p_reasoning_effort",
          "type": "text"
        },
        {
          "name": "p_goal_mode",
          "type": "boolean"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "create_subtasks": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        },
        {
          "name": "p_parent_task_id",
          "type": "uuid"
        },
        {
          "name": "p_claim_token_hash",
          "type": "text"
        },
        {
          "name": "p_subtasks",
          "type": "jsonb"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "create_user_artifact": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        },
        {
          "name": "p_task_id",
          "type": "uuid"
        },
        {
          "name": "p_artifact_id",
          "type": "uuid"
        },
        {
          "name": "p_name",
          "type": "text"
        },
        {
          "name": "p_mime_type",
          "type": "text"
        },
        {
          "name": "p_size",
          "type": "bigint"
        },
        {
          "name": "p_storage_path",
          "type": "text"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "create_user_subtasks": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        },
        {
          "name": "p_parent_task_id",
          "type": "uuid"
        },
        {
          "name": "p_subtasks",
          "type": "jsonb"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "create_user_task": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        },
        {
          "name": "p_parent_task_id",
          "type": "uuid"
        },
        {
          "name": "p_title",
          "type": "text"
        },
        {
          "name": "p_description",
          "type": "text"
        },
        {
          "name": "p_acceptance_criteria",
          "type": "text"
        },
        {
          "name": "p_priority",
          "type": "integer"
        },
        {
          "name": "p_position",
          "type": "integer"
        },
        {
          "name": "p_assigned_session_id",
          "type": "uuid"
        },
        {
          "name": "p_required_capabilities",
          "type": "text[]"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "dispatch_session_turn_chain": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        },
        {
          "name": "p_titles",
          "type": "jsonb"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "enqueue_ai_file_command": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        },
        {
          "name": "p_command_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_action",
          "type": "text"
        },
        {
          "name": "p_path",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "enqueue_ai_thread_command": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        },
        {
          "name": "p_command_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        },
        {
          "name": "p_action",
          "type": "text"
        },
        {
          "name": "p_name",
          "type": "text"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "enqueue_ai_thread_command_with_directory": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        },
        {
          "name": "p_command_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        },
        {
          "name": "p_action",
          "type": "text"
        },
        {
          "name": "p_name",
          "type": "text"
        },
        {
          "name": "p_directory_key",
          "type": "text"
        },
        {
          "name": "p_platform",
          "type": "text"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    },
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        },
        {
          "name": "p_command_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        },
        {
          "name": "p_action",
          "type": "text"
        },
        {
          "name": "p_name",
          "type": "text"
        },
        {
          "name": "p_directory_key",
          "type": "text"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "enqueue_ai_thread_command_with_settings": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        },
        {
          "name": "p_command_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        },
        {
          "name": "p_action",
          "type": "text"
        },
        {
          "name": "p_name",
          "type": "text"
        },
        {
          "name": "p_directory_key",
          "type": "text"
        },
        {
          "name": "p_model",
          "type": "text"
        },
        {
          "name": "p_reasoning_effort",
          "type": "text"
        },
        {
          "name": "p_platform",
          "type": "text"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    },
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        },
        {
          "name": "p_command_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        },
        {
          "name": "p_action",
          "type": "text"
        },
        {
          "name": "p_name",
          "type": "text"
        },
        {
          "name": "p_directory_key",
          "type": "text"
        },
        {
          "name": "p_model",
          "type": "text"
        },
        {
          "name": "p_reasoning_effort",
          "type": "text"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "ensure_personal_workspace": [
    {
      "args": [
        {
          "name": "p_name",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 1
    }
  ],
  "exchange_ai_connection_bridge_config": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_runtime_instance_id",
          "type": "uuid"
        },
        {
          "name": "p_report_sequence",
          "type": "bigint"
        },
        {
          "name": "p_lease_seconds",
          "type": "integer"
        },
        {
          "name": "p_release_runtime",
          "type": "boolean"
        },
        {
          "name": "p_applied_version",
          "type": "integer"
        },
        {
          "name": "p_effective",
          "type": "jsonb"
        },
        {
          "name": "p_constraints",
          "type": "jsonb"
        },
        {
          "name": "p_error",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    },
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_platform",
          "type": "text"
        },
        {
          "name": "p_runtime_instance_id",
          "type": "uuid"
        },
        {
          "name": "p_report_sequence",
          "type": "bigint"
        },
        {
          "name": "p_lease_seconds",
          "type": "integer"
        },
        {
          "name": "p_release_runtime",
          "type": "boolean"
        },
        {
          "name": "p_applied_version",
          "type": "integer"
        },
        {
          "name": "p_effective",
          "type": "jsonb"
        },
        {
          "name": "p_constraints",
          "type": "jsonb"
        },
        {
          "name": "p_error",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "fail_task": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        },
        {
          "name": "p_task_id",
          "type": "uuid"
        },
        {
          "name": "p_claim_token_hash",
          "type": "text"
        },
        {
          "name": "p_reason",
          "type": "text"
        },
        {
          "name": "p_result_json",
          "type": "jsonb"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "heartbeat_ai_session": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "heartbeat_claim": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        },
        {
          "name": "p_task_id",
          "type": "uuid"
        },
        {
          "name": "p_claim_token_hash",
          "type": "text"
        },
        {
          "name": "p_lease_seconds",
          "type": "integer"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "import_session_history": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        },
        {
          "name": "p_runtime_instance_id",
          "type": "uuid"
        },
        {
          "name": "p_report_sequence",
          "type": "bigint"
        },
        {
          "name": "p_items",
          "type": "jsonb"
        },
        {
          "name": "p_sync",
          "type": "jsonb"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "is_workspace_member": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        }
      ],
      "returns": "boolean",
      "defaults": 0
    },
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        }
      ],
      "returns": "boolean",
      "defaults": 0
    }
  ],
  "is_workspace_owner": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        }
      ],
      "returns": "boolean",
      "defaults": 0
    },
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        }
      ],
      "returns": "boolean",
      "defaults": 0
    }
  ],
  "pause_task": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        },
        {
          "name": "p_task_id",
          "type": "uuid"
        },
        {
          "name": "p_reason",
          "type": "text"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "poll_task_user_input_request": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        },
        {
          "name": "p_task_id",
          "type": "uuid"
        },
        {
          "name": "p_claim_token_hash",
          "type": "text"
        },
        {
          "name": "p_request_id",
          "type": "uuid"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "post_task_message": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        },
        {
          "name": "p_task_id",
          "type": "uuid"
        },
        {
          "name": "p_claim_token_hash",
          "type": "text"
        },
        {
          "name": "p_content",
          "type": "text"
        },
        {
          "name": "p_reply_to_message_id",
          "type": "uuid"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "post_user_task_message": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        },
        {
          "name": "p_task_id",
          "type": "uuid"
        },
        {
          "name": "p_content",
          "type": "text"
        },
        {
          "name": "p_reply_to_message_id",
          "type": "uuid"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "register_ai_session": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_name",
          "type": "text"
        },
        {
          "name": "p_platform",
          "type": "text"
        },
        {
          "name": "p_model",
          "type": "text"
        },
        {
          "name": "p_external_conversation_ref",
          "type": "text"
        },
        {
          "name": "p_capabilities",
          "type": "text[]"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "register_task_user_input_request": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        },
        {
          "name": "p_task_id",
          "type": "uuid"
        },
        {
          "name": "p_claim_token_hash",
          "type": "text"
        },
        {
          "name": "p_request_id",
          "type": "uuid"
        },
        {
          "name": "p_external_request_id",
          "type": "text"
        },
        {
          "name": "p_turn_id",
          "type": "text"
        },
        {
          "name": "p_item_id",
          "type": "text"
        },
        {
          "name": "p_is_blocking",
          "type": "boolean"
        },
        {
          "name": "p_questions",
          "type": "jsonb"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "release_task": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        },
        {
          "name": "p_task_id",
          "type": "uuid"
        },
        {
          "name": "p_claim_token_hash",
          "type": "text"
        },
        {
          "name": "p_reason",
          "type": "text"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "release_task_by_user": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        },
        {
          "name": "p_task_id",
          "type": "uuid"
        },
        {
          "name": "p_reason",
          "type": "text"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "rename_ai_connection": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_name",
          "type": "text"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "reopen_task": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        },
        {
          "name": "p_task_id",
          "type": "uuid"
        },
        {
          "name": "p_reason",
          "type": "text"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "reply_to_task": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        },
        {
          "name": "p_task_id",
          "type": "uuid"
        },
        {
          "name": "p_content",
          "type": "text"
        },
        {
          "name": "p_reply_to_message_id",
          "type": "uuid"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "report_current_task": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        },
        {
          "name": "p_title",
          "type": "text"
        },
        {
          "name": "p_description",
          "type": "text"
        },
        {
          "name": "p_acceptance_criteria",
          "type": "text"
        },
        {
          "name": "p_external_source",
          "type": "text"
        },
        {
          "name": "p_external_task_ref",
          "type": "text"
        },
        {
          "name": "p_external_conversation_ref",
          "type": "text"
        },
        {
          "name": "p_priority",
          "type": "integer"
        },
        {
          "name": "p_progress_note",
          "type": "text"
        },
        {
          "name": "p_progress_percent_estimate",
          "type": "integer"
        },
        {
          "name": "p_required_capabilities",
          "type": "text[]"
        },
        {
          "name": "p_claim_token_hash",
          "type": "text"
        },
        {
          "name": "p_lease_seconds",
          "type": "integer"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "report_progress": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        },
        {
          "name": "p_task_id",
          "type": "uuid"
        },
        {
          "name": "p_claim_token_hash",
          "type": "text"
        },
        {
          "name": "p_progress_note",
          "type": "text"
        },
        {
          "name": "p_progress_percent_estimate",
          "type": "integer"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "report_session_activity": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        },
        {
          "name": "p_task_id",
          "type": "uuid"
        },
        {
          "name": "p_claim_token_hash",
          "type": "text"
        },
        {
          "name": "p_kind",
          "type": "text"
        },
        {
          "name": "p_content",
          "type": "text"
        },
        {
          "name": "p_data",
          "type": "jsonb"
        },
        {
          "name": "p_external_ref",
          "type": "text"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "request_user_input": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_session_id",
          "type": "uuid"
        },
        {
          "name": "p_task_id",
          "type": "uuid"
        },
        {
          "name": "p_claim_token_hash",
          "type": "text"
        },
        {
          "name": "p_question",
          "type": "text"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "resume_task": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        },
        {
          "name": "p_task_id",
          "type": "uuid"
        },
        {
          "name": "p_reason",
          "type": "text"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "revoke_ai_connection": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_reason",
          "type": "text"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "rotate_ai_connection": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_token_hash",
          "type": "text"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "sync_ai_sessions": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_bridge_version",
          "type": "text"
        },
        {
          "name": "p_platform",
          "type": "text"
        },
        {
          "name": "p_threads",
          "type": "jsonb"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    },
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_bridge_version",
          "type": "text"
        },
        {
          "name": "p_threads",
          "type": "jsonb"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "sync_ai_sessions_with_directories": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_bridge_version",
          "type": "text"
        },
        {
          "name": "p_platform",
          "type": "text"
        },
        {
          "name": "p_directories",
          "type": "jsonb"
        },
        {
          "name": "p_threads",
          "type": "jsonb"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    },
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_api_token_hash",
          "type": "text"
        },
        {
          "name": "p_bridge_version",
          "type": "text"
        },
        {
          "name": "p_directories",
          "type": "jsonb"
        },
        {
          "name": "p_threads",
          "type": "jsonb"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "update_ai_connection_bridge_config": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_expected_version",
          "type": "integer"
        },
        {
          "name": "p_enabled",
          "type": "boolean"
        },
        {
          "name": "p_include_thread_titles",
          "type": "boolean"
        },
        {
          "name": "p_max_threads",
          "type": "integer"
        },
        {
          "name": "p_max_concurrent_turns",
          "type": "integer"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    },
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_platform",
          "type": "text"
        },
        {
          "name": "p_expected_version",
          "type": "integer"
        },
        {
          "name": "p_enabled",
          "type": "boolean"
        },
        {
          "name": "p_include_thread_titles",
          "type": "boolean"
        },
        {
          "name": "p_max_threads",
          "type": "integer"
        },
        {
          "name": "p_max_concurrent_turns",
          "type": "integer"
        },
        {
          "name": "p_sync_history",
          "type": "boolean"
        },
        {
          "name": "p_history_turn_limit",
          "type": "integer"
        },
        {
          "name": "p_working_directories",
          "type": "jsonb"
        },
        {
          "name": "p_permission_mode",
          "type": "text"
        },
        {
          "name": "p_approval_mode",
          "type": "text"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    },
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_expected_version",
          "type": "integer"
        },
        {
          "name": "p_enabled",
          "type": "boolean"
        },
        {
          "name": "p_include_thread_titles",
          "type": "boolean"
        },
        {
          "name": "p_max_threads",
          "type": "integer"
        },
        {
          "name": "p_max_concurrent_turns",
          "type": "integer"
        },
        {
          "name": "p_sync_history",
          "type": "boolean"
        },
        {
          "name": "p_history_turn_limit",
          "type": "integer"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    },
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_expected_version",
          "type": "integer"
        },
        {
          "name": "p_enabled",
          "type": "boolean"
        },
        {
          "name": "p_include_thread_titles",
          "type": "boolean"
        },
        {
          "name": "p_max_threads",
          "type": "integer"
        },
        {
          "name": "p_max_concurrent_turns",
          "type": "integer"
        },
        {
          "name": "p_sync_history",
          "type": "boolean"
        },
        {
          "name": "p_history_turn_limit",
          "type": "integer"
        },
        {
          "name": "p_working_directories",
          "type": "jsonb"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    },
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        },
        {
          "name": "p_connection_id",
          "type": "uuid"
        },
        {
          "name": "p_platform",
          "type": "text"
        },
        {
          "name": "p_expected_version",
          "type": "integer"
        },
        {
          "name": "p_enabled",
          "type": "boolean"
        },
        {
          "name": "p_include_thread_titles",
          "type": "boolean"
        },
        {
          "name": "p_max_threads",
          "type": "integer"
        },
        {
          "name": "p_max_concurrent_turns",
          "type": "integer"
        },
        {
          "name": "p_sync_history",
          "type": "boolean"
        },
        {
          "name": "p_history_turn_limit",
          "type": "integer"
        },
        {
          "name": "p_working_directories",
          "type": "jsonb"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
  "update_user_task": [
    {
      "args": [
        {
          "name": "p_workspace_id",
          "type": "uuid"
        },
        {
          "name": "p_user_id",
          "type": "uuid"
        },
        {
          "name": "p_task_id",
          "type": "uuid"
        },
        {
          "name": "p_patch",
          "type": "jsonb"
        },
        {
          "name": "p_idempotency_key",
          "type": "text"
        },
        {
          "name": "p_request_hash",
          "type": "text"
        }
      ],
      "returns": "jsonb",
      "defaults": 0
    }
  ],
};
